apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimad_frontend-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: digimad_frontend
          image: digimad_frontend_image
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: digimad_frontend-service
spec:
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  type: LoadBalancer
  selector:
    app: nodejs
  externalIPs:
   - 10.128.14.10