
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimad-frontend-deployment
  namespace: testing
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: digimad-frontend
          image: 10.128.14.150/library/digimad_frontend_image
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: digimad-frontend-service
  namespace: testing
spec:
  ports:
  - protocol: TCP
    #port: 4200
    port: 443
    targetPort: 443
    nodePort: 31420
  type: LoadBalancer
  selector:
    app: nodejs
  externalIPs:
   - 10.128.14.10
