apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimad-ai-computer-vision-deployment-production
  namespace: production
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: digimad-ai-computer-vision-production
          image: 10.128.14.150/library/digimad_backend_ai_computer_vision_image_production
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: digimad-ai-computer-vision-service-production
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30400
  type: LoadBalancer
  selector:
    app: python
  externalIPs:
   - 10.128.14.10
