apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimad-frontend-deployment-production
  namespace: production
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: digimad-frontend-production
          image: 10.128.14.150/library/digimad_frontend_image_production
          ports:
            - containerPort: 433
---
apiVersion: v1
kind: Service
metadata:
  name: digimad-frontend-service-production
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 433
    targetPort: 433
    nodePort: 30420
  type: LoadBalancer
  selector:
    app: nodejs
  externalIPs:
   - 10.128.14.110
