
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimad-backend-ai-model-deployment
  namespace: testing
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: digimad-backend-ai-model
          image: 10.128.14.150/library/digimad_backend_ai_model_image
          ports:
            - containerPort: 31900
---
apiVersion: v1
kind: Service
metadata:
  name: digimad-backend-ai-model-service
  namespace: testing
spec:
  ports:
  - protocol: TCP
    port: 31900
    targetPort: 31900
    nodePort: 31900
  type: LoadBalancer
  selector:
    app: python
  externalIPs:
   - 10.128.14.10
